server:
  port: 8763

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: service-provider
  zipkin:
    base-url: http://127.0.0.1:9411/

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      label: master
      profile: dev

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: linkinstar
    password: linkinstar

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh





